apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 8.6.1   # stable version
    helm:
      valueFiles:
        - values.yaml
      valuesFiles:
        - https://raw.githubusercontent.com/lgtmstack-pixel/Grafana/main/blackbox-exporter/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: blackbox

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
