apiVersion: v2
name: alertmanager
description: Alertmanager Helm chart for GitOps deployment
type: application
version: 0.1.0

dependencies:
  - name: alertmanager
    repository: https://prometheus-community.github.io/helm-charts
    version: 0.27.0


