apiVersion: v2
name: alertmanager
description: Alertmanager Helm chart for GitOps deployment
type: application
version: 0.1.0

dependencies:
  - name: alertmanager
    version: 1.13.2
    repository: https://prometheus-community.github.io/helm-charts

