apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    alertmanager: prometheus-alertmanager
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 30900
