apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: http
      nodePort: 30900

