apiVersion: v2
name: prometheus
version: 0.1.0

dependencies:
  - name: prometheus
    version: 25.21.0
    repository: https://prometheus-community.github.io/helm-charts

  - name: prometheus-blackbox-exporter
    version: 8.7.0
    repository: https://prometheus-community.github.io/helm-charts


